apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-container
        image: jeevanclk/ultimate:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-dockerhub-secret
