apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: jeevan
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
