apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: jeevan
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8020
  type: LoadBalancer
